### ISSUE TITLE
FINOS Infra : Creation of additional FINOS CCC distribution lists

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#101]
@TheJuanAndOnly99 and @maoo 

Would it be possible to create the following lists on Groups.IO for the FINOS CCC project in addition to [ccc-participants](https://lists.finos.org/g/ccc-participants).

- [ ] ccc-maintainers
- [ ] ccc-taxonomy
- [ ] ccc-mitre
- [ ] ccc-oscal
- [ ] Please post a link to each new list and associated email subscription so FINOS CCC participants can subscribe for updates.

Thanks so much 🌟 

James.

cc @finos/ccc-maintainers

**Comment by njwilliams** [comment]
My summary of the discussion: Although we want to try and capture all information in the single place (github), there are some people who would like to contribute who do not have a github account. It would be good to have an alternative. That's why the request for a distribution list. Proposal: have a "contacting us" set of guidelines that says what content to put where (and when to copy content between different mediums) to make sure we have appropriate usage. For now, use/advertise ccc-participants list for non github comms and see what the volume is like before creating a bunch of WG based groups.

**Comment by crawfordchanel** [comment]
I agree with Nick. Ideally, we want to collectively manage the CCC project in GitHub and work together there, however, there are access issues, permissions, and legal hoops some contributors have to jump through that makes it difficult to participate. It is also extremely time consuming to go back through all updates and identify what work has been completed, tasks assigned, discussions etc. that pertain to your interest in the project. I think for now, DL's are necessary until we get to a point of maturity where all participants have access with ease.

**Comment by iMichaela** [comment]
How the work on documents OR OSCAL formatting will be performed and coordinated via email? who will emerge the comments and address conflicts? 
Matrix.org purchased Gitter which was natively integrated with GitHub, so, IF Matrix.org is used, people can join **with**  their GH accounts OR **without** GH account (with a Matrix (free) account) . Files can be also attached and GH issues directly linked. Just my 2 cents.

**Comment by crawfordchanel** [comment]
Community agreed not to utilize DL's
