### ISSUE TITLE
08/01/2024 All Hands Meeting Minutes

### ISSUE THREAD

**Issue by eddie-knight** [finos/common-cloud-controls#288]
## Date

08/01/2024 - 12:00 ET / 17:00 UK

- [Join Zoom Meeting](https://zoom.us/j/94416168360)
- Meeting ID: 944 1616 8360
- Passcode: 042805
- [Find your local number](https://zoom.us/u/apjhwwA3K)
- [Copy this meeting to your calendar](calendar.finos.org)

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).
- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).
- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.
- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] [Project board](https://github.com/orgs/finos/projects/78/views/11) walkthrough
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Untracked attendees

- Fullname, Affiliation, (optional) GitHub username
- ...

**Comment by jared-lambert** [comment]
Jared Lambert / Microsoft

**Comment by damienjburks** [comment]
Damien Burks / Citi 👋🏾

**Comment by eddie-knight** [comment]
👋 :shipit: Eddie Knight / Sonatype

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by sshiells-scottlogic** [comment]
Stevie Shiells / Scott Logic

**Comment by mlysaght2017** [comment]
Michael Lysaght / Citi

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🐨

**Comment by sshiells-scottlogic** [comment]
Minutes:

EK: opened the call
EK: meeting notices, prev mins.
EK: Called out for mentoring at least one other approvers to streamline and remove bottlenecks.
EK: WG updates
JL: New  “resources” folder articulate various types of resources we are leveraging.
2 or 3 folks improving those going deeper into particular areas.
Using board/backlog to direct efforts.
New person join and putting them to work.
Slow but steady, need more people to assign work to. Easy space to get involved. 
ML: Security WG – Open PR on extending object storage security controls catalog. Aligned with EK template. Good conversation in WG.
PR up for RDMS controls.
LSEG starting to implement OSCAL.

EK : On PR, Taxonomy WG getting flagged as codeowner as new directory as tests. Can ML review that is exactly how we want to structure the organization of security artifacts. If so we can structure codeowners so that not blocked.
DB: Delivery WG making steady progress. GitHub actions merged in for linting and formatting.
Discussions on releasing and versioning strategies. Still in process of finalizing those things.
SS: Link checker added, meeting template adjusted to reflect WG name/meeting times. First draft of release/milestone guidance added.
SS: On behalf of SM and taxonomy: 
1.	Refactor RDMS - Ivan / Scott Logic
2.	NoSQL - Sonali / Scott Logic
3.	Graph Database - Eric
4.	Guidelines and Template for taxonomy definitions – Eddie
RM: Discussion with SS about getting Colin from SL to see if can help to get an adopter for AI security controls.
JL: Have a call set up on Tuesday but Colin couldn’t connect. Call went on, AI workstream asked to setup use case and can we take that setup the controls.
All agree that is what we want to do.
List of services
What controls do we need.
Banks want this right now.
Could be opportunity for more people to get involved if we are focusing on a hot topic.

EK: Create a milestone based on JL describing and meets ML expectations

Group: Created [milestone for RAG LLM](https://github.com/finos/common-cloud-controls/milestone/6) and related issues.
