### ISSUE TITLE
Define vision and purpose for OSCAL Representation of CCC working group

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#42]
_**Due date : 20th October 2023**_

This GitHub issues represents part of the roadmap defined by the OSCAL working group on https://github.com/finos/common-cloud-controls/issues/13
```[tasklist]
### Tasks
- [x] Define vision and purpose for NIST / OSCAL working group
- [x] Define the end target for the working group - For example, stop regenerating processes
```

**Comment by mcleo-d** [comment]
@jonmuk, @iMichaela and @rachkim00 

It would be great to bring this issue to conclusion. There is great content in the comments that should be transferred into the repo as a markdown doc or inner ReadMe.

It would be great to get your guidance on how to close.

James.

**Comment by rachkim00** [comment]
Based on the comment history, here's the vision I have summed up:

1. Work with industry partners to define how to represent the CCC in OSCAL. Including threats (leveraging MITRE), controls and test cases.
2. If this requires changes to OSCAL, work with NIST community to discuss changes, note this may not be required.
3. The expected output would be:

- A definition of where these elements are represented
- CCC OSCAL Control Catalog, Profile and/or Component definition of each major CSP services.

4.  Establish a framework and change management process to update FINOS CCC in OSCAL as regulatory, control, and other compliance frameworks evolve and change

@jonmuk and @iMichaela, if you both agree, we can publish this as our vision and close this issue.

**Comment by robmoffat** [comment]
This was discussed in the CCC All Hands meeting today.  @iMichaela requested that the sample OSCAL from @l1ttlej1m 's white paper be contributed as `text` to the CCC repository so that it could be iterated upon.  

Dropping this request here as it seems like part of the vision @rachkim00 outlines above.

@maoo  @karlmoll

**Comment by robmoffat** [comment]
Looking at the PDF this appears to be just an image - @crawfordchanel to ask @l1ttlej1m for the original source code.

**Comment by rachkim00** [comment]
> Looking at the PDF this appears to be just an image - @crawfordchanel to ask @l1ttlej1m for the original source code. @rachkim00 will summarise in README once she has this.

@crawfordchanel Hi Chanel- any updates on the original source code?

**Comment by crawfordchanel** [comment]
Hi @rachkim00 @iMichaela 

Yes. Here is the original code from the Citi Whitepaper

controls:
- id: M1032
class: MITRE Att&amp;ck
title: Multi-Factor Authentication
params:
props:
- name: label
value: M1032
class: MITRE Att&amp;ck
- name: sort-id
value: M1032
links:
- href: &quot;#M1032&quot;
rel: required
- href: &quot;#M1026&quot;
rel: related
- href: &quot;#M1018&quot;
rel: related
- href: &quot;#CCC.M1&quot;
rel: related
parts:
- id: M1032_smt
name: statement
prose: &quot;Multi Factor Authentication&quot;
parts:
- id: M1032_smt.CCC.C1
name: item
props:
- name: label

value: (CCC.C1)
prose: &quot;Platform must enforce authentication with MFA.&quot;
- id: M1032_smt.CCC.C2
name: item
props:
- name: label
value: (CCC.C2)
prose: &quot; Local authentication must be disabled or restricted.&quot;
- id: M1032_smt.CCC.C3
name: item
props:
- name: label
value: (CCC.C3)
prose: &quot;Monitor API action that disables MFA.&quot;
- id: M1032_smt.CCC.C4
name: item
props:
- name: label
value: (CCC.C4)
prose: &quot;Monitor for database actions to related to local authentication.&quot;
- id: M1032_gdn
name: guidance
prose: &quot;Use two or more pieces of evidence to authenticate to a system; such as username and
password in addition to a token from a physical smart card or token generator.&quot;
- id: M1032_obj
name: assessment-objective
props:
- name: label
value: M1032

class: CCC
parts:
- id: M1032_obj.CCC.C1
name: assessment-objective
class: preventative
props:
- name: label
value: (CCC.C1)
prose: &quot;Use two or more pieces of evidence to authenticate to a system; such as username and
password in addition to a token from a physical smart card or token generator.&quot;
- id: M1032_obj.CCC.C2
name: assessment-objective
class: preventative
props:
- name: label
value: (CCC.C2)
prose: &quot;Local Authentication must be disabled and only allow multi-factor authentication.&quot;
- id: M1032_obj.CCC.C3
name: assessment-objective
class: detective
props:
- name: label
value: (CCC.C3)
prose: &quot;Attempt to disable multi-factor authentication are recorded, monitored and alerted on.&quot;
- id: M1032_obj.CCC.C4
name: assessment-objective
class: detective
props:
- name: label

value: (CCC.C4)
prose: &quot;Successful attempt to use local authentication to access a resource should be monitored
and alerted on.&quot;
- id: M1032_asm-examine
name: assessment-method
props:
- name: method
ns: ... #namespace to CCC
value: EXAMINE
- name: label
value: M1032-Examine
class: CCC
parts:
- name: assessment-objects
prose: &gt;-
CSP Identification and authentication policy
Cloud Service Authentication policy
Procedures addressing authenticator management
System security plan
System design documentation
System configuration settings and associated documentation
Other relevant documents or records
- id: M1032_asm-validate
name: assessment-method
props:
- name: method
ns: ... #namespace to FSC2
value: Validate
- name: label

value: M1032-Validate
class: CCC
parts:
- name: assessment-objects
prose: Mechanisms supporting and/or implementing password-based
authenticator management capability

- id: M1032_asm-validate
name: assessment-method
props:
- name: method
value: Validate
ns: ... #namespace to CCC
class: CCC
- name: label
value: M1032-Validate
class: CCC
parts:
- id: M1032_asm-validate.CCC.C1
name: validate
props:
- name: method
value: (CCC.C1)
class: preventative
prose: &quot;GIVEN Cloud Platform WHEN principle attempts authentication to perform API action

THEN platform must enforce multi-factor authentication for each user&quot;

- id: M1032_asm-validate.CCC.C2
name: validate
props:

- name: method
value: (CCC.C2)
class: preventative
prose: &quot;GIVEN cloud service WHEN principle attempts authentication to the service with

local credential THEN service should deny action for all principles&quot;

- id: M1032_asm-validate.CCC.C3
name: validate
props:
- name: method
value: (CCC.C3)
class: detective
prose: &quot;GIVEN MFA is enabled on cloud service WHEN authentication attempt is successful.
and MFA age is &#39;0&#39; or &#39;null&#39; and MFA authentication token present=false THEN
record the action and alert&quot;
- id: M1032_asm-validate.CCC.C4
name: validate
props:
- name: method
value: (CCC.C4)
class: detective
prose: &quot;GIVEN cloud service WHEN principle attempts authentication to service with

local credential THEN record the action and alert&quot;

**Comment by iMichaela** [comment]
@crawfordchanel - Thank you for the provided information. Is anyone that generated the data that we can talk with to clearly it? I have to confess, I do not understand what was the intend to represent. From the pdf document I gather the following

In OSCAL,  a control is anything a system/service needs to implement and with needs to be assessed. 
- Controls can be nested:a parent control can have children controls, especially when a child control makes no sense or cannot exist without it's parent.  
For example  "Implement MFA" can be a parent control, and can have "Platform must enforce authentication with MFA" as a child control, because unless you implement MFA, the platform has nothing to enforce.
- Control ID's should be sortable, support paren-child relations, and allow tools to reconstruct the information for a human to review. So I am including in the table below zero-leading numeral proceeded by C (from control). Note: it can me any letter or structure of the ID
- Sort labels are used to sort the information and be able to render it for a human, and are not needed if control's ID are the same.
- refs can me relative and internal to the document, but cannot to point to itself
- An objective can be a control-objective (what a control needs to achieve) or an assessment-objective ( what needs to be assessed), but should not be confused with he statement of a control
- An assessment-objective can be paired with one or more assessment-method(s) (how to determine the assessment-objectives are met). Often, authoritive entities might limit what assessment-methods are allowed: test:- yes, documentation review:- no; interview:- no; or allow the method to be selected.

|  GROUP ID | GROUP TTITLE  |  CONTROL ID   |  CONTROL TITLE  |  MITIGATED THREAD | CONTROL CLASS | CONTROL STATEMENT  |   GUIDANCE | HAS PARENT  |
| :---       |      :----:   |  :----:   |     :----:   |     :----:   |      :----:   |      :----:   |         :----:   |      ---: |
|   IA   |   Identification and Authentication   |   C001-M1032 |  Multi-Factor Authentication |   | mitre-attack | Implement multi-factor authentication for access to accounts. | Use two or more pieces of evidence to authenticate to a system; such as username and password in addition to a token from a physical smart card or token generator |     |
|         |          | C001.C1 |          |           |  ccc-preventative | Platform must enforce authentication with MFA. |     |  C001-M1032  |
|         |          | C001.C2 |          |           |  ccc-preventative | Local Authentication must be disabled and only allow multi-factor authentication. |     |  C001-M1032  |
|         |          | C001.C3 |          |           |  ccc-detective | Monitor API action that disables MFA. |     | C001-M1032  |
|         |          | C001.C4 |          |           |  ccc-detective | Successful attempt to use local authentication to access a resource should be monitored and alerted on. |     | C001-M1032  |

In the content provided above by you there is some data that  I do not understand and I will need the original information to judge how to best represent it in OSCAL. Can you point to the page of the white paper from where the information is coming?
Also, if there is listed data in the header but there is no need for such information (e.g. mitigated threat) . please comment and I will remove it.

Last, we need a Markdown sample catalog and its XML representation. Where can they be create those files.
Once the file is created, the https://vierwer.oscal.io/catalog can be used to visualize the data.

**Comment by crawfordchanel** [comment]
Hi Michaela

The text provided is copied and pasted from the published FINOS CCC whitepaper. Section 3.6 “Logical Controls to Extended OSCAL” – pages 21-23. Please note, by the next OSCAL WG meeting, we will have a designated lead who will be more equipped to guide the team through Issue 42.

In the meantime, I will contact the Citi CCC team to address markdown catalogue ownership, its XML representation and where we will create it.

Thank you,


***@***.***
Chanel Crawford - VP
CTO Policy, Innovation Enablement and Strategy
Operations & Technology
3800 Citibank Center | Tampa, Florida 33610
E-mail: ***@***.******@***.***>

**Comment by iMichaela** [comment]
@crawfordchanel - What is the "Extended OSCAL" mentioned in the document? OSCAL has native extension mechanisms but those are not the ones used in the example. Is there the Citi's intention to create and maintain an "Extended OSCAL" specification and a registry of all the namespaces (ns) proposed in the example?

**Comment by rachkim00** [comment]
Based on today's (2/8) discussion, I will draft readme.md with reference to [CFI readme.md](https://github.com/finos/compliant-financial-infrastructure) and share with the community for more feedback/finalization.

**Comment by crawfordchanel** [comment]
Merge complete
