### ISSUE TITLE
MITRE WG: Establish collaboration with OSCAL working group on schema 

### ISSUE THREAD

**Issue by nas-hub** [finos/common-cloud-controls#75]
### Objectives
1. Define the location within the OSCAL schema for embedding Control Testing Requirements.
2. Define the location within the OSCAL schema for embedding abstract testing language (Gherkins).

**Comment by nas-hub** [comment]
For the very first cloud domain RDBMS, the testing requirements have been defined leveraging machine readable abstract language (Gherkins). They are defined https://github.com/finos/common-cloud-controls/blob/main/services/database/relational/rdms-taxonomy.feature

As these machine readable testing requirements are being defined, it is right time to discuss where to reference this data in OSCAL schema. We can also discuss if we embed the data in OSCAL file or do we reference to the testing requirements file from OSCAL structure. 

+ing @rachkim00 @iMichaela  for their guidance here.

@eddie-knight FYI

**Comment by rachkim00** [comment]
Thanks @nas-hub for looping us in. 

Question - do we want to keep this gherkins format as is or are we looking to expand what's currently written in Gherkins to OSCAL structure? 

Depending on the approach, I think different OSCAL models can be suggested: If we want to use gherkins as the format/place to document the assessment plan, we can just reference in out [componen](https://pages.nist.gov/OSCAL-Reference/models/v1.1.0/component-definition/json-outline/)t or [control catalog](https://pages.nist.gov/OSCAL-Reference/models/v1.1.0/catalog/json-outline/) as props in each components/controls; if we want to embed testing scenario fully in OSCAL format, then[ Security Assessment Plan](https://pages.nist.gov/OSCAL-Reference/models/v1.1.0/assessment-plan/json-outline/) mode it is.

**Comment by nas-hub** [comment]
Yes, gherkins data will be by itself (like a text blob or reference to the location of text blob), this way we can have CSP agnostic common assessments for each of the Capability defined by the Taxonomy team.

Does it then make sense to keep this data in the [OSCAL: Security Assessment Plan](https://pages.nist.gov/OSCAL-Reference/models/v1.1.0/assessment-plan/json-outline/).

**Comment by rachkim00** [comment]
If this is going to be the assessment plan used to actual assessment, not the suggested guide, then yes, Security Assessment Plan as the place. I think we need to decide on specifically where to refer Gherkins test data within SAP taxonomy. 

I am thinking: Security Assessment Plan > Tasks > Associated-activities > prop { name: 'test name', ns = finos_ccc (example), value: url to the gherkins}. 

@iMichaela does it make sense? is this way possible?

**Comment by iMichaela** [comment]
@rachkim00  - Yes, the `Security Assessment Plan > Tasks ` will capture the assessment task, and the gherkin script can be described and linked as `Security Assessment Plan > Tasks > Associated-activity` but I wonder if you used the `prop` because it has a `uuid` and you expect the `uuid` to be updated in the SAR any time when the script gets updated, or is there another reason for selecting `prop` and not `link` /`links` with a `rel="gherkins"`. 
Note that the `associated-activities` have `uuids too. There is really not wrong way of doing it, but rather optimal way depending on how the information is used and by whom. 
It is important to remember that GRC tools which know OSCAL will ignore any other `ns` unless there is a registry for those extensions form where they can learn how to use the extensions.

![SAR_1](https://github.com/finos/common-cloud-controls/assets/13984545/5c5e01fc-a3c2-4106-aa82-d94b3f21a861)

## The descriptions are below:

[Security Assessment Plan > Tasks](https://pages.nist.gov/OSCAL-Reference/models/v1.1.1/assessment-plan/xml-reference/#/assessment-plan/task)
[Security Assessment Plan > Tasks > Associated-activity](https://pages.nist.gov/OSCAL-Reference/models/v1.1.1/assessment-plan/xml-reference/#/assessment-plan/task/associated-activity)
[Security Assessment Plan > Tasks > Associated-activity > link](https://pages.nist.gov/OSCAL-Reference/models/v1.1.1/assessment-plan/xml-reference/#/assessment-plan/task/associated-activity/link)
[Security Assessment Plan > Tasks > Associated-activity > prop](https://pages.nist.gov/OSCAL-Reference/models/v1.1.1/assessment-plan/xml-reference/#/assessment-plan/task/associated-activity/prop)

**Comment by rachkim00** [comment]
You got it right- I picked 'Prop' over 'Link' because of the UUID and version control, assuming that Gherkin scripts will evolve and change over the time. Also, one of the items we (OSCAL Working group) discussed was version control- so I thought UUID could help us with that
