### ISSUE TITLE
November 30th 2023 Common Cloud Controls - Define Cloud Services Taxonomy

### ISSUE THREAD

**Issue by mcleo-d** [finos/common-cloud-controls#92]
## Date
November 30th 2023 - 12pm ET / 5pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [ ] Kanban review and milestone planning - https://github.com/orgs/finos/projects/78/views/2
- [ ] AOB, Q&A & Adjourn (5mins)

### Zoom info
Join Zoom Meeting
https://zoom.us/j/98254617376?pwd=aGV6VzZQOTg3MHptY0tkZHRVSUsxUT09

Meeting ID: 982 5461 7376
Passcode: 305874

---

Dial by your location
• +1 719 359 4580 US
• +1 253 205 0468 US
• +1 253 215 8782 US (Tacoma)
• +1 301 715 8592 US (Washington DC)
• +1 305 224 1968 US
• +1 309 205 3325 US
• +1 312 626 6799 US (Chicago)
• +1 346 248 7799 US (Houston)
• +1 360 209 5623 US
• +1 386 347 5053 US
• +1 507 473 4847 US
• +1 564 217 2000 US
• +1 646 558 8656 US (New York)
• +1 646 931 3860 US
• +1 669 444 9171 US
• +1 669 900 6833 US (San Jose)
• +1 689 278 1000 US
• 855 880 1246 US Toll-free
• 877 369 0926 US Toll-free
• +1 438 809 7799 Canada
• +1 587 328 1099 Canada
• +1 647 374 4685 Canada
• +1 647 558 0588 Canada
• +1 778 907 2071 Canada
• +1 780 666 0144 Canada
• +1 204 272 7920 Canada
• 855 703 8985 Canada Toll-free

Meeting ID: 982 5461 7376

Find your local number: https://zoom.us/u/acPjHdY2IO

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by eziogas-scottlogic** [comment]
Euthyme Ziogas / Scott Logic

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by crawfordchanel** [comment]
Chanel Crawford / Citi

**Comment by selgags** [comment]
Anna Selyugina / Goldman Sachs

**Comment by smendis-scottlogic** [comment]
Sonali Mendis / Scott Logic

**Comment by crawfordchanel** [comment]
Kanban review and milestone planning
JM: MITRE and OSCAL groups have been running groups through the Kanban. We are starting to align the working groups to milestones created by the WG themselves but in the future, we will have a “standards oversight” committee to help with prioritization. But here and now, I am going to ask AS-FSI if they are okay with the Kanban route or another way?

AS – For me, Kanban is fine. But I would like a dedicated distribution list.

JM – Feedback on that. If we go to Kanban view, I raised an issue for that. Kanban has been created for the taxonomy WG. FINOS CCC is now a Kanban. Taxonomy, OSCAL and MITRE and a combined WG. For today’s call I will go through what the other groups are doing. We work from right to left. Done, in progress and prioritized.

Seven items completed. A number were previous mtgs. We have a pull requestthat was closed and not merged. When the first taxonomy was reviewed, therewas work done in a spreadsheet. Conversation has moved forward since thenand that PR turned irrelevant.

#85 – EK/SM – This was addition to what I have committed in the first place. We did not have failover as a control in RDMS taxonomy and I added it. EK first reviewed. It was later merged by AH. I think we are good. We can close it.

AH – This was really great input the demos that EK did at OSFF. Good work and useful work but we need to revisit to finalize in terms of an RDS taxonomy would be my assumption. I do not know what other banks think whether it needs another review based on the original Citi RDS work that was done?

RG – If the original whitepaper work preexisted, why did we do this in the first place?

AH – We did not have access

JM – The whitepaper has already been published. This whitepaper is viewable even though it is not merged. It could be a comparison of the taxonomy piece from RDS. Its not only RDS but MITRE as well. It under the ownership of the
project instead of the ownership of Citi.

AH – I think we need a new issue to compare the current RDS work that has been merged and the Citi whitepaper and update the current work where appropriate. – I will open a new issue up to take this own. I will open two issues.

JM – PR is #85 and the whitepaper

EK – We want to formalize the presentation. The format. How are we presenting all these taxonomies.

RG – should be standardize the way the taxonomy is describe

JM – OB – I am not sure whether you have written an issue, but your team has an overview of the CDMC taxonomy. Rather than opening a new issue is there one that already exists?

OB – There is one out there. But it is at a high level when we talked to JA and CL. It is an info model that describes requirements and can be mapped. AWS google Azure and snowflake have all published their framework. What we don’t know is what stage in CCC should we plug these in? We need a mtg with various subsets of working groups to see how this can work. Part of the goal of CCC is what controls are available.

JM – CDMC perspective. The Focus perspective through FINOS. Now we have the Citi perspective through the whitepaper. We have 3 points of view. Instead of writing new ones to see how it should be done. We should bring it all together.

EK – CDMC integration should be a steering committee.

OB – Cloud companies have already done the control work. We must map it to CCC. All 4 popular platforms already have this. It allows us to refer to one classification etc.

JM – CDMC is like a matrix after taxonomy has been defined in CCC.

OB – Or we use CDMC as the mapping.

AH – The starting point is the Citi work. I have not read it yet. I can pick up that PR and merge it I will. I will update the issue.

JM – Me and Chanel will work on getting it all published.

JM – MM has moved on from Citi. Issue #94- Needs updated. Moe would like to remain as a maintainer in the project. He understands the capacity. I have updated the issue and closed it as well. The maintainer role is with the individual not the firm. MR is the person representing Citi in this group.

RG – Who is playing the role as the project owner? Who provides requirements? Who is raising issues?

JM – That is a good question. It falls into the scope of the entire project. We were thinking about lead maintainers, the banks should be lead maintainers. With the 3 WG there are 3 banking main per WG. Because of the holiday, we did not have the discussion. When it comes to product owner role, decided that title is too authoritative. So, we are going to do a steering committee. JA has agreed to join the steering committee. The requirements for the standards will come from the white paper. He will help the maintainers prioritize the future. But we want more ppl on the steering committee. I am leaving the organization. We will have prioritization sessions before I leave so we can get Q1 priorities sorted.

EZ – From a practical point of view we had a working version of RDMS, and OSFF was great but what are we working on next? The last thing I want my team to do is waste their time on something and someone else is doing it.

EK – The steerco should have public meetings for feedback, ask questions, general direction of things. Please include that in the constitution for the steerco.

JM – Being able to vote on a steerco. CCC came from Jim and team. The person closest to it understand purpose direction and scope.

RG – Just to be clear, they do not actually own it. It is FINOS now.

RG – To get things moving faster, we will start a list of topics of things and create an issue for each one. The maintainers can duke it out as to who will own what. I am not suggesting a detailed list, but maybe a small number.

JM – You can raise issues for what you want. I think everything in the kanban in progress is a high-level view of the question you were asking.

RG – That list was made august 31 st and the last comment was in September. So, it is not really active.

EK – That is refining the top-level taxonomy only, right?

JM – Let us not burn time on issues that have not been prioritized.

RG – Maybe we can start with the top two.

EK – Keep in mind. End user demand as a prioritization driver. Contributor interest – contributor interest could be prompted by the list. Or we can just grab things that you really want to work on.

SM – We have a few categorizations that are done already. We looked at focus CDMC and the first ask should be to produce the top-level taxonomy.

EK – Question for SM - considering that is a steering level kind of thing – can these be two independent work items? Or are these waterfall related? We must have the op level in order to do anything.

SM – No you are right without top level taxonomy we can work on low hanging fruit. But right now, we are not sure of the direction. 

JM – The maintainers of the WG’s – mark from Citi – Simon from BMO, AS from Goldman, I think the actual maintainers will work with steerco to define priorities. Steerco has not been created yet; we are looking to bring the maintainers together with Jim. This time next week we have a project all hands. Prioritization will not come out of this meeting. But the steerco will take care of this. It will be the banking leads who run this. What EK is saying we can have a good gut feel on what the taxonomy items will be.

JM - The first mtg will be the 12th of December and the next one will be the 14th . #56 – Jason and the MITRE group were defining Storage. I think that is done. AS is this done?

AS – I do not t think I am actively contributing to any issues.

EK – Will there be a coupling with MITRE

AS – There is a ticket for it with taxonomy to align with MITRE

EK – If we are struggling to see how they align that is something else we can work on for right now.

SM – CDMC covers storage.

JM – CDMC works under a diff license level than CCC. So, Oli – we do have a project where we can put CDMC a tech spec under the right license to be open sourced. It is under a free license.

EK – I am the maintainer for that project.

JM – OB - take the email you wrote and convert it to an issue.

OB – I think I did that already.

JM – I will get this scheduled so we can have the discussion. I will get JA meeting going so everyone is aware what is going on. I am moving away from FINOS, and I have invited RM from FINOS and he will be representing FINOS going forward.
